[project]
name = "python-exercism"
project_name = "python-exercism"
version = "0.1.0"
description = "Solutions to exercism exercises"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9"

[[project.authors]]
name = "Roger Hughes"
email = "roger@roghu.com"

[tool.black]
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[build-system]
requires = ["setuptools >= 57.4.0", "wheel"]
build-backend = "setuptools.build_meta"
