name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Setup up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install dependences
        run: |
          python -m pip install tox-gh-actions
          python -m poetry install

      - name: Tests
        run: python -m poetry run tox -e py

      - name: Flake8
        run: python -m poetry run tox -e flake8

      - name: typing
        run: python -m poetry tox -e typing

      - name: Upload results to codecov
        if: success()
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
