name: Tests

on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v1

      - name: Setup up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v2.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-pep582: true

      - name: Tests
        run: nox -s tests

      - name: Flake8
        run: nox -s flake8

      - name: typing
        run: nox -s typing

      - name: coverage
        if: success()
        run: nox -s coverage

      - name: Upload results to codecov
        if: success()
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
